No secrets found. Valid paths for a secrets.toml file or secret directories are:
C:\Users\Admin\.streamlit\secrets.toml
C:\Users\Admin\Desktop\trails\.streamlit\secrets.toml
OPENAI_API_KEY="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"
openai.api_key = OPENAI_API_KEY
